# Generated by Django 5.2 on 2025-07-24 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="phone",
            field=models.CharField(
                max_length=15, unique=True, verbose_name="Номер телефона"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="username",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="Ваш email"
            ),
        ),
    ]
