# Generated by Django 5.2 on 2025-07-24 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_customuser_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="phone",
            field=models.CharField(max_length=20, verbose_name="Номер телефона"),
        ),
    ]
