# Generated by Django 5.2 on 2025-07-24 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_customuser_phone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="wants_school_diary",
        ),
    ]
