# Generated by Django 5.2 on 2025-07-22 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DiaryEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Заголовок")),
                ("text", models.TextField()),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("is_private", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Запись дневника",
                "verbose_name_plural": "Записи дневника",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="GradeRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subject",
                    models.CharField(max_length=50, verbose_name="Название предмета"),
                ),
                ("grade", models.CharField(max_length=3, verbose_name="Оценка")),
                ("date", models.DateField(verbose_name="Дата записи")),
                (
                    "homework",
                    models.TextField(
                        blank=True, null=True, verbose_name="Домашнее задание"
                    ),
                ),
                (
                    "reminder",
                    models.TextField(blank=True, null=True, verbose_name="Напоминание"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SchoolDiary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
