# Generated by Django 5.2 on 2025-07-27 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="diaryentry",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="diary_files/"),
        ),
    ]
