# Generated by Django 5.2 on 2025-07-22 19:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("diary", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="diaryentry",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="diary_entries",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Ваш никнейм",
            ),
        ),
        migrations.AddField(
            model_name="schooldiary",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="graderecord",
            name="diary",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="diary.schooldiary"
            ),
        ),
    ]
