# Generated by Django 5.2 on 2025-07-24 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="diaryentry",
            options={
                "ordering": ["-date", "-updated_at"],
                "verbose_name": "Запись дневника",
                "verbose_name_plural": "Записи дневника",
            },
        ),
        migrations.AddField(
            model_name="diaryentry",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="diaryentry",
            name="is_private",
            field=models.BooleanField(default=True, verbose_name="Приватно"),
        ),
        migrations.AlterField(
            model_name="diaryentry",
            name="text",
            field=models.TextField(verbose_name="Текст"),
        ),
    ]
