# Generated by Django 5.2 on 2025-07-27 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0002_diaryentry_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fileattachment",
            name="diary_entry",
        ),
        migrations.AddField(
            model_name="fileattachment",
            name="entry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="diary.diaryentry",
            ),
        ),
    ]
