# Generated by Django 5.2 on 2025-07-25 12:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0003_alter_diaryentry_options_diaryentry_updated_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FileAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="diary_attachments/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf", "jpg", "png", "docx"]
                            )
                        ],
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("color", models.CharField(default="#007bff", max_length=7)),
            ],
        ),
        migrations.AddField(
            model_name="diaryentry",
            name="files",
            field=models.ManyToManyField(blank=True, to="diary.fileattachment"),
        ),
        migrations.AddField(
            model_name="diaryentry",
            name="tags",
            field=models.ManyToManyField(blank=True, to="diary.tag"),
        ),
    ]
