# Generated by Django 5.2 on 2025-07-25 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0004_fileattachment_tag_diaryentry_files_diaryentry_tags"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="diaryentry",
            name="files",
        ),
        migrations.AddField(
            model_name="fileattachment",
            name="diary_entry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="file_attachments",
                to="diary.diaryentry",
            ),
        ),
        migrations.AddField(
            model_name="fileattachment",
            name="uploaded_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="DiaryFileAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attached_at", models.DateTimeField(auto_now_add=True)),
                (
                    "diary_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="diary.diaryentry",
                    ),
                ),
                (
                    "file_attachment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="diary.fileattachment",
                    ),
                ),
            ],
            options={
                "unique_together": {("diary_entry", "file_attachment")},
            },
        ),
        migrations.AddField(
            model_name="diaryentry",
            name="attachments",
            field=models.ManyToManyField(
                blank=True,
                related_name="entries",
                through="diary.DiaryFileAttachment",
                to="diary.fileattachment",
            ),
        ),
    ]
