# Generated by Django 5.2 on 2025-07-26 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0005_remove_diaryentry_files_fileattachment_diary_entry_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diaryentry",
            name="attachments",
            field=models.ManyToManyField(
                blank=True,
                related_name="entries",
                through="diary.DiaryFileAttachment",
                to="diary.fileattachment",
                verbose_name="Загрузить файл",
            ),
        ),
        migrations.AlterField(
            model_name="diaryentry",
            name="tags",
            field=models.ManyToManyField(
                blank=True, to="diary.tag", verbose_name="Теги"
            ),
        ),
    ]
