# Generated by Django 5.2 on 2025-07-26 16:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0006_alter_diaryentry_attachments_alter_diaryentry_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fileattachment",
            name="file",
            field=models.FileField(
                upload_to="diary_attachments/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "jpg", "png", "docx"]
                    )
                ],
                verbose_name="Загрузить файл",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=50, unique=True, verbose_name="Теги"),
        ),
    ]
