name: Django CI

on: [ push, pull_request ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install flake8
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Run Flake8
        run: flake8 .

  test:
    runs-on: ubuntu-latest
    needs: lint
    postgres:
        image: postgres-latest
        env:
          POSTGRES_NAME: ${{NAME}}
          POSTGRES_PASSWORD: ${{PASSWORD}}
          POSTGRES_USER: ${{USER}}
          POSTGRES_HOST: db
          POSTGRES_PORT: ${{PORT}}


    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'


      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-key: ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt          
          pip install -r requirements-dev.txt          
          pip install flake8 pytest-django

      - name: Run flake8
        run: flake8 .

      - name: Run tests
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/db_mylifem
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: |
          python manage.py test

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/MyLifeM:${{ github.sha }} .

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/MyLifeM:${{ github.sha }}


  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Install dependencies on server
        run: |
          ssh -o StrictHostKeyChecking=no -vT ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/MyLifeM:${{ github.sha }}
          docker stop MyLifeM || true
          docker rm MyLifeM || true
          docker run -d --name MyLifeM \
            -p 80:8000 \
            -e "ENV_VAR=value" \
            ${{ secrets.DOCKERHUB_USERNAME }}/MyLifeM:${{ github.sha }}
          EOF